# GameMode config (из NixOS modules/system/core/gamemode.nix)
[general]
renice=5
softrealtime=auto

[cpu]
governor=schedutil

[custom]
start=notify-send "GameMode started"
end=notify-send "GameMode ended"
